// Generated by gencpp from file first_pkg/srv1.msg
// DO NOT EDIT!


#ifndef FIRST_PKG_MESSAGE_SRV1_H
#define FIRST_PKG_MESSAGE_SRV1_H

#include <ros/service_traits.h>


#include <first_pkg/srv1Request.h>
#include <first_pkg/srv1Response.h>


namespace first_pkg
{

struct srv1
{

typedef srv1Request Request;
typedef srv1Response Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct srv1
} // namespace first_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::first_pkg::srv1 > {
  static const char* value()
  {
    return "4bac5263dd214a8605f1874d4917e35b";
  }

  static const char* value(const ::first_pkg::srv1&) { return value(); }
};

template<>
struct DataType< ::first_pkg::srv1 > {
  static const char* value()
  {
    return "first_pkg/srv1";
  }

  static const char* value(const ::first_pkg::srv1&) { return value(); }
};


// service_traits::MD5Sum< ::first_pkg::srv1Request> should match 
// service_traits::MD5Sum< ::first_pkg::srv1 > 
template<>
struct MD5Sum< ::first_pkg::srv1Request>
{
  static const char* value()
  {
    return MD5Sum< ::first_pkg::srv1 >::value();
  }
  static const char* value(const ::first_pkg::srv1Request&)
  {
    return value();
  }
};

// service_traits::DataType< ::first_pkg::srv1Request> should match 
// service_traits::DataType< ::first_pkg::srv1 > 
template<>
struct DataType< ::first_pkg::srv1Request>
{
  static const char* value()
  {
    return DataType< ::first_pkg::srv1 >::value();
  }
  static const char* value(const ::first_pkg::srv1Request&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::first_pkg::srv1Response> should match 
// service_traits::MD5Sum< ::first_pkg::srv1 > 
template<>
struct MD5Sum< ::first_pkg::srv1Response>
{
  static const char* value()
  {
    return MD5Sum< ::first_pkg::srv1 >::value();
  }
  static const char* value(const ::first_pkg::srv1Response&)
  {
    return value();
  }
};

// service_traits::DataType< ::first_pkg::srv1Response> should match 
// service_traits::DataType< ::first_pkg::srv1 > 
template<>
struct DataType< ::first_pkg::srv1Response>
{
  static const char* value()
  {
    return DataType< ::first_pkg::srv1 >::value();
  }
  static const char* value(const ::first_pkg::srv1Response&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FIRST_PKG_MESSAGE_SRV1_H
